#端口
server:
  port: 9001
#微服务id
spring:
  application:
    name: tensquare-base
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.207.111:3306/tensquare_base?characterEncoding=UTF-8
    username: root
    password: root
  jpa:
    show-sql: true
#eureka配置
eureka:
  client:
    #开发阶段的其他配置
    registry-fetch-interval-seconds: 5  #拉取注册信息
    instance-info-replication-interval-seconds: 5  #替换信息
    service-url:
      defaultZone: http://localhost:10086/eureka/ 
  instance:
    prefer-ip-address: true #上报ip地址给注册中心
    lease-renewal-interval-in-seconds: 5 #开发阶段改为5秒发一次心跳
