#端口
server:
  port: 10086
#微服务id
spring:
  application:
    name: register-center
#eureka配置
eureka:
  client:
    #开发阶段的其他配置
    registry-fetch-interval-seconds: 5  #拉取注册信息
    instance-info-replication-interval-seconds: 5  #替换信息
    service-url:
      defaultZone: http://localhost:10086/eureka/ 
  server:
    enable-self-preservation: false  #开发阶段关闭自我保护模式
    eviction-interval-timer-in-ms: 5000  #每隔5秒进行一次服务列表清理